// Code generated by fastssz. DO NOT EDIT.
// Hash: 5ebfebd09b74413c237f87a592266bffd79e51534b0c63d0af6d48313f344ddc
// Version: 0.1.2
package altair

import (
	"github.com/attestantio/go-eth2-client/spec/phase0"
	ssz "github.com/ferranbt/fastssz"
)

// MarshalSSZ ssz marshals the LightClientHeader object
func (l *LightClientHeader) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(l)
}

// MarshalSSZTo ssz marshals the LightClientHeader object to a target array
func (l *LightClientHeader) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(4)

	// Offset (0) 'Beacon'
	dst = ssz.WriteOffset(dst, offset)
	if l.Beacon == nil {
		l.Beacon = new(phase0.BeaconBlockHeader)
	}
	offset += l.Beacon.SizeSSZ()

	// Field (0) 'Beacon'
	if dst, err = l.Beacon.MarshalSSZTo(dst); err != nil {
		return
	}

	return
}

// UnmarshalSSZ ssz unmarshals the LightClientHeader object
func (l *LightClientHeader) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 4 {
		return ssz.ErrSize
	}

	tail := buf
	var o0 uint64

	// Offset (0) 'Beacon'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 < 4 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (0) 'Beacon'
	{
		buf = tail[o0:]
		if l.Beacon == nil {
			l.Beacon = new(phase0.BeaconBlockHeader)
		}
		if err = l.Beacon.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the LightClientHeader object
func (l *LightClientHeader) SizeSSZ() (size int) {
	size = 4

	// Field (0) 'Beacon'
	if l.Beacon == nil {
		l.Beacon = new(phase0.BeaconBlockHeader)
	}
	size += l.Beacon.SizeSSZ()

	return
}

// HashTreeRoot ssz hashes the LightClientHeader object
func (l *LightClientHeader) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(l)
}

// HashTreeRootWith ssz hashes the LightClientHeader object with a hasher
func (l *LightClientHeader) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'Beacon'
	if err = l.Beacon.HashTreeRootWith(hh); err != nil {
		return
	}

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the LightClientHeader object
func (l *LightClientHeader) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(l)
}
