// Code generated by fastssz. DO NOT EDIT.
// Hash: 346ee941df740345c72a6f59d4061030b398f4d6745d5ea5f40bfd7854895799
// Version: 0.1.2
package altair

import (
	"github.com/attestantio/go-eth2-client/spec/phase0"
	ssz "github.com/ferranbt/fastssz"
)

// MarshalSSZ ssz marshals the LightClientOptimisticUpdate object
func (l *LightClientOptimisticUpdate) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(l)
}

// MarshalSSZTo ssz marshals the LightClientOptimisticUpdate object to a target array
func (l *LightClientOptimisticUpdate) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(16)

	// Offset (0) 'AttestedHeader'
	dst = ssz.WriteOffset(dst, offset)
	if l.AttestedHeader == nil {
		l.AttestedHeader = new(phase0.BeaconBlockHeader)
	}
	offset += l.AttestedHeader.SizeSSZ()

	// Offset (1) 'SyncAggregate'
	dst = ssz.WriteOffset(dst, offset)
	if l.SyncAggregate == nil {
		l.SyncAggregate = new(SyncAggregate)
	}
	offset += l.SyncAggregate.SizeSSZ()

	// Field (2) 'SignatureSlot'
	dst = ssz.MarshalUint64(dst, uint64(l.SignatureSlot))

	// Field (0) 'AttestedHeader'
	if dst, err = l.AttestedHeader.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (1) 'SyncAggregate'
	if dst, err = l.SyncAggregate.MarshalSSZTo(dst); err != nil {
		return
	}

	return
}

// UnmarshalSSZ ssz unmarshals the LightClientOptimisticUpdate object
func (l *LightClientOptimisticUpdate) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 16 {
		return ssz.ErrSize
	}

	tail := buf
	var o0, o1 uint64

	// Offset (0) 'AttestedHeader'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 < 16 {
		return ssz.ErrInvalidVariableOffset
	}

	// Offset (1) 'SyncAggregate'
	if o1 = ssz.ReadOffset(buf[4:8]); o1 > size || o0 > o1 {
		return ssz.ErrOffset
	}

	// Field (2) 'SignatureSlot'
	l.SignatureSlot = phase0.Slot(ssz.UnmarshallUint64(buf[8:16]))

	// Field (0) 'AttestedHeader'
	{
		buf = tail[o0:o1]
		if l.AttestedHeader == nil {
			l.AttestedHeader = new(phase0.BeaconBlockHeader)
		}
		if err = l.AttestedHeader.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}

	// Field (1) 'SyncAggregate'
	{
		buf = tail[o1:]
		if l.SyncAggregate == nil {
			l.SyncAggregate = new(SyncAggregate)
		}
		if err = l.SyncAggregate.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the LightClientOptimisticUpdate object
func (l *LightClientOptimisticUpdate) SizeSSZ() (size int) {
	size = 16

	// Field (0) 'AttestedHeader'
	if l.AttestedHeader == nil {
		l.AttestedHeader = new(phase0.BeaconBlockHeader)
	}
	size += l.AttestedHeader.SizeSSZ()

	// Field (1) 'SyncAggregate'
	if l.SyncAggregate == nil {
		l.SyncAggregate = new(SyncAggregate)
	}
	size += l.SyncAggregate.SizeSSZ()

	return
}

// HashTreeRoot ssz hashes the LightClientOptimisticUpdate object
func (l *LightClientOptimisticUpdate) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(l)
}

// HashTreeRootWith ssz hashes the LightClientOptimisticUpdate object with a hasher
func (l *LightClientOptimisticUpdate) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'AttestedHeader'
	if err = l.AttestedHeader.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (1) 'SyncAggregate'
	if err = l.SyncAggregate.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (2) 'SignatureSlot'
	hh.PutUint64(uint64(l.SignatureSlot))

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the LightClientOptimisticUpdate object
func (l *LightClientOptimisticUpdate) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(l)
}
